### ISSUE TITLE
一调openGallery就报子线程异常

### ISSUE THREAD

**Issue by dengyuhan** [FinalTeam/RxGalleryFinal#112]
![image](https://cloud.githubusercontent.com/assets/17588779/25211407/b6309b08-25b7-11e7-9bfd-dcffe123406a.png)

```
FATAL EXCEPTION: RxIoScheduler-2
    Process: com.digizen.g2u, PID: 11100
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
    Caused by: java.lang.NoSuchMethodError: No direct method lambda$generateBuckets$0(Lrx/Subscriber;)V in class Lcn/finalteam/rxgalleryfinal/interactor/impl/MediaBucketFactoryInteractorImpl; or its super classes (declaration of 'cn.finalteam.rxgalleryfinal.interactor.impl.MediaBucketFactoryInteractorImpl' appears in /data/app/com.digizen.g2u-1/base.apk:classes27.dex)
    at cn.finalteam.rxgalleryfinal.interactor.impl.MediaBucketFactoryInteractorImpl.access$lambda$0(MediaBucketFactoryInteractorImpl.java)
    at cn.finalteam.rxgalleryfinal.interactor.impl.MediaBucketFactoryInteractorImpl$$Lambda$1.call(Unknown Source)
    at rx.Observable.unsafeSubscribe(Observable.java:10151)
    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
    at java.lang.Thread.run(Thread.java:761) 
```

**Comment by sheep0704** [comment]
新版测试下

**Comment by xiliangxiaoke** [comment]
也是遇到这个问题，不知道怎么解决，与demo一模一样的代码，但demo没有问题，RxJava的版本也是一样的
