### ISSUE TITLE
1.0.3大BUG，picasso预览大图崩溃

### ISSUE THREAD

**Issue by 39251474** [FinalTeam/RxGalleryFinal#119]
升级到1.0.3后换回picasso加载方式，小图没有问题，点击查看大图时直接崩溃。使用centerCrop()必须调用resize()设置宽或高，不然就抛异常。
if(resize){
            creator = creator.resize(width, height).centerCrop();// 放这里
        }

**Comment by sheep0704** [comment]
GET.THANKS

**Comment by sheep0704** [comment]
try compile 'cn.finalteam.rxgalleryfinal:library:1.0.4'

**Comment by sheep0704** [comment]
网络问题, 周一出现。

**Comment by epolar** [comment]
同点击大图崩溃，日志：
java.lang.NullPointerException: Attempt to get length of null array
                                                                   at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.radioNext(MediaGridFragment.java:451)
                                                                   at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onObItemClick(MediaGridFragment.java:390)
                                                                   at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onItemClick(MediaGridFragment.java:374)
                                                                   at cn.finalteam.rxgalleryfinal.ui.widget.FooterAdapter.lambda$onBindViewHolder$9(FooterAdapter.java:40)
                                                                   at cn.finalteam.rxgalleryfinal.ui.widget.FooterAdapter.access$lambda$0(FooterAdapter.java)
                                                                   at cn.finalteam.rxgalleryfinal.ui.widget.FooterAdapter$$Lambda$1.onClick(Unknown Source)
                                                                   at android.view.View.performClick(View.java:5226)
                                                                   at android.view.View$PerformClick.run(View.java:21266)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:168)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5781)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by sheep0704** [comment]
@epolar  try compile 'cn.finalteam.rxgalleryfinal:library:1.0.4'

**Comment by 39251474** [comment]
@sheep0704 不对啊，看你源代码  if(resize)  上面的centerCrop()没有删掉，你确定Jcenter上的版本是正确的？

**Comment by sheep0704** [comment]
@39251474 我=检查下

**Comment by sheep0704** [comment]
thks，go 1.0.5

**Comment by liuyu1212120** [comment]
try compile 'cn.finalteam.rxgalleryfinal:library:1.0.6'

**Comment by sheep0704** [comment]
try compile 'cn.finalteam.rxgalleryfinal:library:1.0.6' @39251474
