### ISSUE TITLE
使用Glide方式显示图片崩溃

### ISSUE THREAD

**Issue by himon** [FinalTeam/RxGalleryFinal#136]
Demo测试，如果把Fresco.initialize(this);注释了，使用ImageLoaderType.GLIDE方式显示图片会崩溃
错误信息：
 Process: cn.finalteam.rxgalleryfinal.sample, PID: 26863
                                                                                    android.view.InflateException: Binary XML file line #30: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                        at cn.finalteam.rxgalleryfinal.ui.adapter.MediaGridAdapter.onCreateViewHolder(MediaGridAdapter.java:92)
                                                                                        at cn.finalteam.rxgalleryfinal.ui.adapter.MediaGridAdapter.onCreateViewHolder(MediaGridAdapter.java:49)
                                                                                        at cn.finalteam.rxgalleryfinal.ui.widget.FooterAdapter.onCreateViewHolder(FooterAdapter.java:32)
                                                                                        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5833)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5057)
                                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
                                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                                        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:541)
                                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                                        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                        at android.view.View.layout(View.java:14834)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4635)
                                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                                    	at android.view.ViewRootImpl.performTra

**Comment by liuyu1212120** [comment]
马上修复
