### ISSUE TITLE
Android4.4.4崩溃

### ISSUE THREAD

**Issue by sclgithub** [FinalTeam/RxGalleryFinal#143]
Android5.1系统运行正常，Android4.4.4崩溃，: 
Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
06-09 12:23:34.019 3539-3539/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.senyint.MAPatient, PID: 3539
                                                 java.lang.VerifyError: cn/finalteam/rxgalleryfinal/ui/adapter/MediaGridAdapter
                                                     at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onViewCreatedOk(MediaGridFragment.java:196)
                                                     at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:63)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)

**Comment by ljf1172361058** [comment]
我也碰到这问题了

**Comment by 7449** [comment]
@ljf1172361058 等新版本，或者直接下载Library
