### ISSUE TITLE
华为荣耀4.4报错

### ISSUE THREAD

**Issue by iammasir** [FinalTeam/RxGalleryFinal#146]
java.lang.VerifyError: cn/finalteam/rxgalleryfinal/ui/adapter/MediaGridAdapter

**Comment by iammasir** [comment]
java.lang.VerifyError: cn/finalteam/rxgalleryfinal/ui/adapter/MediaGridAdapter
                                                       at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onViewCreatedOk(MediaGridFragment.java:196)
                                                       at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:63)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                       at cn.finalteam.rxgalleryfinal.ui.activity.BaseActivity.onStart(BaseActivity.java:74)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1175)
                                                       at android.app.Activity.performStart(Activity.java:5313)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                       at dalvik.system.NativeStart.main(Native Method)
06-14 19:12:08.233 1032-1043/? W/ActivityManager:   Force finishing activity com.example.dia/cn.finalteam.rxgalleryfinal.ui.activity.MediaActivity
06-14 19:12:08.233 1032-1043/? W/ActivityManager:   Force finishing activity com.example.dia/.MainActivity

**Comment by crzaycat** [comment]
红米1S也是同样的报错

**Comment by crzaycat** [comment]
@iammasir 请问你解决了吗？

**Comment by 7449** [comment]
运行sample也报错吗？还是依赖的gradle

**Comment by crzaycat** [comment]
运行sample正常，但是在项目中就报错

**Comment by 7449** [comment]
你可以试试直接依赖Library,不要依赖gradle，Library代码比较新，还没有推新版本

**Comment by crzaycat** [comment]
就是直接依赖的Library

**Comment by 7449** [comment]
用的Glide？还是其他的图片加载框架

**Comment by 7449** [comment]
如果是最新的Library，用 Fresco 也报错吗？之前有人反馈过这个问题，当时在他反馈的机型上已经弄好了，不知道为什么又复现了

**Comment by crzaycat** [comment]
glide，没有用Fresco

**Comment by KarelGT** [comment]
Glide 红米HM2A Android4.4.4遇到同样Crash
cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onViewCreatedOk(MediaGridFragment.java:196
cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:63)

**Comment by KarelGT** [comment]
我这边尝试了源码导入可以解决

**Comment by sheep0704** [comment]
经测试没有问题，可检查下代码相关的调用

**Comment by epolar** [comment]
4.4.2 4.4.4两个系统均出现这个错误，测试机型有：酷派大神F2，红米2A，华为荣耀

**Comment by epolar** [comment]
1.0.9似乎解决了这个问题了
