### ISSUE TITLE
项目中使用了Lambda表达式就无法使用

### ISSUE THREAD

**Issue by QiYan925** [FinalTeam/RxGalleryFinal#151]
报错如下：  
Caused by: java.lang.NoSuchMethodError: cn.finalteam.rxgalleryfinal.interactor.impl.MediaSrcFactoryInteractorImpl.cn_finalteam_rxgalleryfinal_interactor_impl_MediaSrcFactoryInteractorImpl_lambda$generateMeidas$1
                                                                                            at cn.finalteam.rxgalleryfinal.interactor.impl.MediaSrcFactoryInteractorImpl.access$lambda$0(MediaSrcFactoryInteractorImpl.java)
                                                                                            at cn.finalteam.rxgalleryfinal.interactor.impl.MediaSrcFactoryInteractorImpl$$Lambda$1.subscribe(Unknown Source)
                                                                                            at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)

**Comment by QiYan925** [comment]
知道原因了，我在代码里使用了

`defaultConfig {
        ...
        jackOptions {
            enabled true
        }
        ...
}`

去掉使用 apply plugin: 'me.tatarka.retrolambda'  即可
