### ISSUE TITLE
有的图片裁剪后报NullPointerException

### ISSUE THREAD

**Issue by amelons** [FinalTeam/RxGalleryFinal#157]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.ArrayList.clear()' on a null object reference
                                                                              at cn.finalteam.galleryfinal.PhotoSelectActivity.onDestroy(PhotoSelectActivity.java:591)
                                                                              at android.app.Activity.performDestroy(Activity.java:6503)
                                                                              at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
                                                                              at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3878)

对应代码：

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mPhotoTargetFolder = null;
        mSelectPhotoMap.clear();
        System.gc();
    }

**Comment by 7449** [comment]
看错误 你依赖的不是最新版？
