### ISSUE TITLE
在5.0以下系统报错

### ISSUE THREAD

**Issue by QianSunny** [FinalTeam/RxGalleryFinal#159]
使用1.07依赖，和直接使用1.08的库，在4.x的系统均报如下错误：
FATAL EXCEPTION: main
                                                   Process: com.wld.net, PID: 27784
                                                   java.lang.VerifyError: cn/finalteam/rxgalleryfinal/ui/adapter/MediaGridAdapter
                                                       at cn.finalteam.rxgalleryfinal.ui.RxGalleryListener.setMultiImageCheckedListener(RxGalleryListener.java:30)
                                                       at com.wld.net.ui.activity.PublishPhotoActivity.setOnClickEvents(PublishPhotoActivity.java:149)
                                                       at com.wld.net.ui.activity.BaseActivity.onCreate(BaseActivity.java:66)
                                                       at android.app.Activity.performCreate(Activity.java:5340)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(Unknown Source)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by sheep0704** [comment]
看下jdk/sdk 版本
