### ISSUE TITLE
有时取到的图片为空的选中之后就会崩溃，自定义单选可裁剪

### ISSUE THREAD

**Issue by lyn370826** [FinalTeam/RxGalleryFinal#175]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66547, result=96, data=Intent { (has extras) }} to activity {cn.zh.base.httpuploadfile/cn.finalteam.rxgalleryfinal.ui.activity.MediaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4115)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4158)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6202)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
	at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onCropFinished(MediaGridFragment.java:662)
	at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onActivityResult(MediaGridFragment.java:646)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:7051)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4111)
	... 9 more

**Comment by sheep0704** [comment]
怎么操作的？

**Comment by Mocaris** [comment]
确实是,这个地方uri.gepath()没有用到,up主 把这个写出来还打了log,结果就是,uri为null

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.1.2'
