### ISSUE TITLE
java.lang.ClassCastException: cn.finalteam.rxgalleryfinal.Configuration cannot be cast to cn.finalteam.rxgalleryfinal.Configuration

### ISSUE THREAD

**Issue by T-BayMax** [FinalTeam/RxGalleryFinal#176]
版本cn.finalteam.rxgalleryfinal:library:1.1.1
使用方法RxGalleryFinalApi.getInstance(MainActivity.this).openGalleryRadioImgDefault(
                                    new RxBusResultDisposable<ImageRadioResultEvent>()

**Comment by 7449** [comment]
没有报错哦，检查下你的代码

**Comment by T-BayMax** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ike.communityalliance/com.ike.communityalliance.loader.a.ActivityN1NRNTS0}: java.lang.ClassCastException: cn.finalteam.rxgalleryfinal.Configuration cannot be cast to cn.finalteam.rxgalleryfinal.Configuration
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6114)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
                                                                     Caused by: java.lang.ClassCastException: cn.finalteam.rxgalleryfinal.Configuration cannot be cast to cn.finalteam.rxgalleryfinal.Configuration
                                                                        at cn.finalteam.rxgalleryfinal.ui.activity.BaseActivity.onCreate(BaseActivity.java:44)
                                                                        at android.app.Activity.performCreate(Activity.java:6736)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6114) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by sheep0704** [comment]
根据demo查看下
