### ISSUE TITLE
#175  并没有解决,MediaGridFragment 642 行,裁剪后  返回的Uri为空

### ISSUE THREAD

**Issue by Mocaris** [FinalTeam/RxGalleryFinal#178]
FATAL EXCEPTION: main
                                                                  Process: com.yhkx.zuoshiapp, PID: 8986
                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66547, result=96, data=Intent { (has extras) }} to activity {com.yhkx.zuoshiapp/cn.finalteam.rxgalleryfinal.ui.activity.MediaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                      at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onCropFinished(MediaGridFragment.java:662)
                                                                      at cn.finalteam.rxgalleryfinal.ui.fragment.MediaGridFragment.onActivityResult(MediaGridFragment.java:646)
                                                                      at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sheep0704** [comment]
GET。
调用场景是怎样？DEMO是否会重现?

**Comment by Mocaris** [comment]
本地有几个以.jpg结尾的文件夹,会显示在相册里面,但实际并不是图片,然后选择单选裁剪后就会报null,就是642那个地方Uri为空,还请尽快修复

**Comment by Mocaris** [comment]
@sheep0704

**Comment by 7449** [comment]
#165 ?  你确定你指的是这个  https://github.com/FinalTeam/RxGalleryFinal/issues/165 ？

**Comment by Mocaris** [comment]
@7449 和#165报的同一个错误,只是不同的场景

**Comment by 7449** [comment]
你指的是 #175 这个吧， #165 没有涉及到 error

**Comment by Mocaris** [comment]
@7449  看错了  是#175 T.T

**Comment by 7449** [comment]
我在根目录下创建了 xxx.jpg 的文件夹 没有显示在 相册中.

RxGalleryFinal版本？
Android版本？
机型？

你是如何复现这个问题的，步骤尽量描述清楚些
☠️

**Comment by Mocaris** [comment]
1.1.1 版本, android 7.1.2, 米5刷的RROS,
 java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.yhkx.zuoshiapp/cache/1501833779810.jpg (No such file or directory)
在打开相册时,会在cache目录下会扫描到1501833779810.jpg文件,但它是个文件夹.好像只有在打开相册后会出现,我也很郁闷

**Comment by 7449** [comment]
待会fix，午休..  cache目录下应该是没有 1501833779810.jpg 这个文件

**Comment by Mocaris** [comment]
3Q

**Comment by sheep0704** [comment]
compile 'cn.finalteam.rxgalleryfinal:library:1.1.2'

**Comment by 15620938955** [comment]
我这边也出现的这个问题（Vivo Vivo NEX A (Android 9, API 28)）这款手机
![image](https://user-images.githubusercontent.com/30037455/59587315-931df480-9117-11e9-9bcd-11768c348c02.png)
麻烦定位处理下，这边很急，谢谢
