### ISSUE TITLE
You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by peach-djf** [FinalTeam/RxGalleryFinal#209]
```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:3937)
	at android.view.ViewGroup.addView(ViewGroup.java:3787)
	at android.view.ViewGroup.addView(ViewGroup.java:3728)
	at cn.finalteam.rxgalleryfinal.a.d$1.onAnimationEnd(SlideOutUnderneathAnimation.java:90)
	at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:854)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
	at android.view.Choreographer.doFrame(Choreographer.java:555)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5265)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

**Comment by sheep0704** [comment]
怎么操作的

**Comment by chenlvmao** [comment]
我也出现这问题  看异常日志才发现的 具体怎么操作还不知道
