### ISSUE TITLE
预览时崩溃

### ISSUE THREAD

**Issue by loshine** [FinalTeam/RxGalleryFinal#21]
这是我调用的代码

```java
        RxGalleryFinal
                .with(getContext())
                .image()
                .multiple()
                .maxSize(9)
                .imageLoader(ImageLoaderType.GLIDE)
                .subscribe(new RxBusResultSubscriber<ImageMultipleResultEvent>() {
                    @Override
                    protected void onEvent(ImageMultipleResultEvent event) throws Exception {
                        Logger.d(event.getResult());
                    }
                })
                .openGallery();
```

当选择照片预览的时候直接崩溃，日志如下：

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.hhly.community.debug, PID: 24482
                                                                          java.lang.VerifyError: Verifier rejected class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter due to bad method android.view.View cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter.getView(int, android.view.View, android.view.ViewGroup) (declaration of 'cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter' appears in /data/data/com.hhly.community.debug/files/instant-run/dex/slice-cn.finalteam.rxgalleryfinal-library-0.0.2_9bf38eb913e0c82c6a8d7ca07550e46787ac621f-classes.dex)
                                                                              at cn.finalteam.rxgalleryfinal.ui.fragment.MediaPageFragment.onViewCreatedOk(MediaPageFragment.java:93)
                                                                              at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:61)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7232)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by loshine** [comment]
另外是否可以增加一个开关来关闭拍摄照片

**Comment by Tobecomebest** [comment]
感谢作者回复，不知是否能尽快解决掉呢？

**Comment by loshine** [comment]
之前同时在项目中 compile 了 RxGalleryFinal 和 PhotoView（因为不知道 RxGalleryFinal 本身已经使用了 PhotoView），然后在去掉了 PhotoView，并把 gradle 中如下修改之后已经不会在预览时报错了

```gradle
    compile("cn.finalteam.rxgalleryfinal:library:$rxgalleryfinal_version",{
        exclude group: 'com.android.support', module: 'recyclerview-v7'
        exclude group: 'com.android.support', module: 'appcompat-v7'
    })
```

不太清除是 PhotoView 冲突导致的问题，还是 support 包冲突导致的问题

**Comment by loshine** [comment]
@Tobecomebest 可以试试我的方法

**Comment by Tobecomebest** [comment]
谢谢，我试试。 @loshine

**Comment by pengjianbo** [comment]
@loshine 你好。新版已经添加了关闭拍照方法，同时也解决了预览图片不清晰问题

**Comment by loshine** [comment]
@pengjianbo 多谢已经用上啦 :)
