### ISSUE TITLE
预览时崩溃，但是demo运行不会出现这个问题

### ISSUE THREAD

**Issue by Tobecomebest** [FinalTeam/RxGalleryFinal#22]
4:02:45.348 20340-20340/com.plusmoney.managerplus E/art: Verification failed on class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter in /data/data/com.plusmoney.managerplus/files/instant-run/dex/slice-cn.finalteam.rxgalleryfinal-library-0.0.2_89365048b80929cdba7f27be78d428b93eec8c73-classes.dex because: Verifier rejected class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter due to bad method android.view.View cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter.getView(int, android.view.View, android.view.ViewGroup)
09-07 14:02:45.348 20340-20340/com.plusmoney.managerplus D/AndroidRuntime: Shutting down VM
09-07 14:02:45.408 20340-20340/com.plusmoney.managerplus E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.plusmoney.managerplus, PID: 20340
                                                                           java.lang.VerifyError: Verifier rejected class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter due to bad method android.view.View cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter.getView(int, android.view.View, android.view.ViewGroup) (declaration of 'cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter' appears in /data/data/com.plusmoney.managerplus/files/instant-run/dex/slice-cn.finalteam.rxgalleryfinal-library-0.0.2_89365048b80929cdba7f27be78d428b93eec8c73-classes.dex)
                                                                               at cn.finalteam.rxgalleryfinal.ui.fragment.MediaPageFragment.onViewCreatedOk(MediaPageFragment.java:93)
                                                                               at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:61)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                               at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                               at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                               at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5287)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by pengjianbo** [comment]
#21
