### ISSUE TITLE
r17 pro不能拍照

### ISSUE THREAD

**Issue by ouyangmingzhuanyong** [FinalTeam/RxGalleryFinal#281]
at android.os.Binder.execTransact(Binder.java:697)
2019-04-18 10:24:55.257 25627-25627/cn.finalteam.rxgalleryfinal.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.finalteam.rxgalleryfinal.sample, PID: 25627
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=25627, uid=10244 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:2029)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1559)
        at cn.finalteam.rxgalleryfinal.RxGalleryFinalApi.openZKCamera(RxGalleryFinalApi.java:297)
        at cn.finalteam.rxgalleryfinal.sample.MainActivity.openImageSelect(MainActivity.java:201)
        at cn.finalteam.rxgalleryfinal.sample.MainActivity.onClick(MainActivity.java:116)
        at android.view.View.performClick(View.java:6407)
        at android.view.View$PerformClick.run(View.java:25175)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7015)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)

**Comment by weiyoupeng** [comment]
是的,拍照就蹦

**Comment by sheep0704** [comment]
GET
