### ISSUE TITLE
10.0系统选择相册时NullPointerException

### ISSUE THREAD

**Issue by epianzhi** [FinalTeam/RxGalleryFinal#311]
BucketAdapter.onBindViewHolder

**Comment by epianzhi** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at cn.finalteam.rxgalleryfinal.ui.adapter.BucketAdapter.onBindViewHolder(BucketAdapter.java:64)
	at cn.finalteam.rxgalleryfinal.ui.adapter.BucketAdapter.onBindViewHolder(BucketAdapter.java:35)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)

**Comment by Panway** [comment]
我今天也碰到了，机型Pixel和Pixel2 Android 10

**Comment by wooodypan** [comment]
Android 10的Pixel2也碰到了此问题，由于此图片选择器常年未更新，现已修改并发布到 https://github.com/wooodypan/RxGalleryFinal
如果有其他的问题，可以自己克隆修改并发布到jitpack.io，本次修改基于原版仓库的2019年4月19日版本
发布到jitpack.io教程参考 https://juejin.cn/post/6844903630412201997 主要流程：clone、修改、本地创建tag并推送到remote、github网页创建release、jitpack搜索选择版本号自动构建、引入

引入方法（不支持AndroidX）：
```
implementation 'com.github.yalantis:ucrop:2.2.3'
implementation 'com.github.wooodypan:RxGalleryFinal:1.20192'
```

PS: 本人是iOS开发😂
