### ISSUE TITLE
无法在图库中重新上传剪裁后crop包下的图片 

### ISSUE THREAD

**Issue by Tmacsy** [FinalTeam/RxGalleryFinal#40]
![Uploading image.png…]()

**Comment by Tmacsy** [comment]
就是第一次上传成功后 会将剪裁后的图片保存在RxGalleryFinal.crop文件夹下  再次上传crop里面的图片时  出现错误 @pengjianbo

**Comment by Tmacsy** [comment]
10-14 10:55:38.192 24584-24584/com.hhly.community.debug E/TransformImageView: onFailure: setImageUri
                                                                              java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:///storage/emulated/0/DCIM/RxGalleryFinal/crop/Screenshot_2016-10-13-16-23-40.png]
                                                                                  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:106)
                                                                                  at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:34)
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by Tmacsy** [comment]
有空麻烦解答一下 谢谢

**Comment by zaxcler** [comment]
这个问题 还没解决吗 @Tmacsy @pengjianbo @suzp1984 # @zshdhr @Liar1995

**Comment by KoalaGH** [comment]
同问
