### ISSUE TITLE
预览图片报错

### ISSUE THREAD

**Issue by TestSmirk** [FinalTeam/RxGalleryFinal#46]
java.lang.VerifyError: Verifier rejected class cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter due to bad method android.view.View cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter.getView(int, android.view.View, android.view.ViewGroup) (declaration of 'cn.finalteam.rxgalleryfinal.ui.adapter.MediaPreviewAdapter' appears in /data/data/xxxxxxx/files/instant-run/dex/slice-cn.finalteam.rxgalleryfinal-library-0.0.3_bf0e8a618bf42f9af3c77cc2ae1f2099236eb26b-classes.dex)
                                                                              at cn.finalteam.rxgalleryfinal.ui.fragment.MediaPageFragment.onViewCreatedOk(MediaPageFragment.java:93)
                                                                              at cn.finalteam.rxgalleryfinal.ui.fragment.BaseFragment.onViewCreated(BaseFragment.java:61)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                              at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

6.0 demo没问题.自己写就这样.

**Comment by zaxcler** [comment]
我也遇到这个问题 系统还是 5.0的 请问 你解决了没

**Comment by TestSmirk** [comment]
没有.

**Comment by zaxcler** [comment]
你的app是不是用了这个分包的 multidex    我测试  不用multidex的app可以正常使用，是不是这个原因呢

**Comment by TestSmirk** [comment]
我没有分包啊. 只是红米和华为个别机型是FC

**Comment by PillarChen** [comment]
我也遇到了这个问题，项目中也确实用了分包的 multidex（项目需要）,自己Demo测试没问题，集成到项目中就出现了现在的问题，测试过library方式，1.0.9 1.1.2 1.1.3版本都这样，怎么解决
