### ISSUE TITLE
单选大图裁剪时候 oom

### ISSUE THREAD

**Issue by 836154942** [FinalTeam/RxGalleryFinal#61]
va.lang.OutOfMemoryError: Failed to allocate a 38340876 byte allocation with 8461058 free bytes and 8MB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
                                                                       at com.yalantis.ucrop.util.BitmapLoadUtils.transformBitmap(BitmapLoadUtils.java:42)
                                                                       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:147)
                                                                       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:34)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by sheep0704** [comment]
fresco
