### ISSUE TITLE
无法裁剪PNG格式图片？

### ISSUE THREAD

**Issue by yinkanghong** [FinalTeam/RxGalleryFinal#77]
裁剪PNG格式图片无结果返回，提示某个接口只支持处理jpg和少量的raw类型文件，错误信息如下：
` Should crop: true
01-11 16:01:30.861 20848-20983/dreamgo.familytree D/uCrop JNI: Crop image with CImg
01-11 16:01:31.299 20848-20983/dreamgo.familytree W/ExifInterface: Invalid image.
                                                                   java.io.IOException: Invalid marker: 89
                                                                       at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1600)
                                                                       at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
                                                                       at android.media.ExifInterface.<init>(ExifInterface.java:1057)
                                                                       at com.yalantis.ucrop.util.ImageHeaderParser.copyExif(ImageHeaderParser.java:404)
                                                                       at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:144)
                                                                       at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:88)
                                                                       at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:30)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)`

**Comment by sheep0704** [comment]
测试中

**Comment by sheep0704** [comment]
无法裁剪PNG格式图片 ---- 新版本1.0.3解决，下午发布；
